- src/index.ts
- src/telegram.ts
As the title suggests, this PR fixes type definitions by using concrete type definitions
> fix: use concrete type definitions instead of any

- README.md
- api/mock/telegram.ts
- mock/async_test.js
- src/constant.ts
- src/telegram.ts
- doc: add promise related reference link
- refactor: rework telegram client logic; adopt async promise
> refactor(handler): rework tg client

- package-lock.json
- package.json
- src/index.ts
- chore(deps): add @types/uuid
- feat: add pr-merged handler
> feat(pull_request): add pr-merge handler

- src/index.ts
- patch(pr.merged): add repo as part of default storage key
- patch(pr.merged): modify default notification msg
> patch(pr.merged): apply minior patches

- src/handler.ts
- src/index.ts
- src/telegram.ts
As the title suggests, this PR apply some code quality fixes to the typescript source code
> chore: apply some code quality fixes

- src/common.ts
- src/config.ts
- src/events/star.created.ts
- src/index.ts
- src/runner.ts
- src/telegram.ts
Introduce some base refactor patterns - will come up with more refinements soon.
> refactor: rework star.created event handler

- src/config.ts
- src/events/pull_request.closed.ts
- src/events/star.created.ts
- src/index.ts
> refactor: rework pull_request.closed event handler

- src/config.ts
- src/events/issue.closed.ts
- src/events/issues.closed.ts
- src/events/issues.opened.ts
- src/index.ts
Rework `issues.opened` and `issues.closed` event handlers
> refactor: rework issue event handler

- src/config.ts
- src/events/pull_request.syncronize.ts
- src/index.ts
As the title suggests - rework `branch-up-to-date` functionality
> refactor: rework pull_request.synchronize event handler

- src/events/pull_request.closed.ts
- src/events/pull_request.opened.ts
- src/events/pull_request.syncronize.ts
As the title suggests. Add extra condition to check if `not-yet-tested` label is eligible to be added to the PR.
> feat(pr.opened): add filter to determine if "not-yet-tested" is eligible

- mock/pr_review_request_test.ts
- package-lock.json
- package.json
- src/events/pull_request.opened.ts
- fixture(mock): test pr_review_request functionality 
- chore(dev-deps): add octokit pkg 
- patch: ONLY request pr review from qa team for dae,daed
> fix(pr.opened): fix broken request-pr-review step

- src/events/pull_request.opened.ts
Add additional condition to handle "fixture" label; fix case: https://github.com/daeuniverse/dae-bot/pull/47
> fix(handler/pr.opened): handle "fixture"  label

- src/events/push.ts
Add default span and error handling for `push` event.
> refactor(handler/push): add default span and error handling

- src/events/pull_request.closed.ts
- src/events/push.ts
Instrument codebase for `pr.closed` handler.
- patch(handler/push): add general tracing refinement
- refactor(handler/pr.closed): add tracing functionality
> feat(handler/pr.close): add tracing functionality

- src/constant.ts
- src/events/pull_request.labeled.ts
- src/events/pull_request.opened.ts
Add tracing support for `pr.labeled` handler
- optimize: import defaultLabels,strictLabels from ./constant
- refactor(handler/pr.labeled): add tracing
> refactor(handler/pr.labeled): add tracing support

- src/events/issues.opened.ts
- refactor(handler/issues.opened): add tracing support
> refactor(handler/issues.opened): add tracing support

- mock/pr_add_assignee_test.ts
- src/events/push.ts
- fixture(mock): add pr_add_assignee_test
- patch(handler/push): fix default assignee
> fixture(mock) add pr_add_assignee test

- src/events/push.ts
- fix(push/sync-upstream): fix broken logic; disable auto_merge
NA
> fix(push/sync-upstream): fix broken logic; disable auto_merge

- src/events/pull_request.closed.ts
- hotfix(pr.closed.release): publish release based on tag ref not HEAD
NA
NA
> hotfix(pr.closed.release): publish release based on tag ref not HEAD

- src/config.ts
- src/events/check_run.completed.ts
- src/events/event_template.ts
- src/events/workflow_run.completed.ts
- src/gateway.ts
- src/index.ts
- src/runner.ts
- patch(gateway): fix incompatible issue
- feat(gateway): log undesired event context
- patch(event_template): fix span closing issue
- patch(gateway): rework check_run event filter
- patch(gateway): set accepted as a class member
- refactor: rename check_runs.completed -> check_run.completed
- fix(workflow_run.completed): apply minor fix
- patch(gateway): don't use async
NA
NA
> patch(check_run.completed): general refinement

- Dockerfile
No need to build container images as the app runs in the form of serverless function.
- ci: get rid of Dockerfile (not needed)
NA
NA
> ci/chore: get rid of Dockerfile (not needed)

- src/events/push.ts
Fix the following issue
- hotfix(push/sync_upstream): fix broken logic
- fix(push/sync_upstream): fix broken syncTarget misreference
NA
NA
> hotfix(push/sync_upstream): fix broken logic

- mock/get_ref_test.ts
Add unit test to fetch commit ref
- fixture(mock): add get_ref_test
NA
NA
> fixture(mock): add ref test

- package-lock.json
- package.json
- src/events/issue_comment.created.ts
Apply markdown formatting with prettier.format
- feat: apply markdown formatting with prettier.format
NA
NA
> feat(issue_comment.created): apply markdown formatting with prettier.format

- src/events/workflow_run.completed.ts
Add condition to handle null syncContext.
- hotfix(workflow_run.completed): add condition to handle null syncContextBody
NA
NA
> hotfix(workflow_run.completed): add condition to handle null syncContext
